### ISSUE TITLE
AWS S3 - java.net.UnknownHostException: repo-user-bucket.s3.us-west-2.amazonaws.com

### ISSUE THREAD

**Issue by AleGallagher** [aws/aws-sdk-java#2396]
I have a service that uses S3 to upload images. When a Run it isolated locally (running only the services's jar in Windows), it works OK. But running it by docker with other services, when I try to upload a image I get this error:

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: repo-user-bucket.s3.us-west-2.amazonaws.com
Caused by: java.net.UnknownHostException: repo-user-bucket.s3.us-west-2.amazonaws.com                                                                                                                           at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_144]
at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_144]
at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_144] 
```
The yml file for the docker compose looks like:

```
version: '2'

services:

  mysqldb:
    image: mysql:5.6.26
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  eureka-service:
    image: services/eureka-server
    ports:
    - "8761:8761"


  image-service:
    image: services/image-service
    ports:
      - "8060:8060"
    links:
      - mysqldb
      - eureka-service
    depends_on:
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=compose
```

The configuraton for the profile compose are:

server.port:8060
spring.application.name=imageService

spring.datasource.url:jdbc:mysql://localhost/db
spring.datasource.username:user
spring.datasource.password:password
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

cloud.aws.region.static:us-west-2
cloud.aws.credentials.accessKey:accessKey
cloud.aws.credentials.secretKey:secretKey
cloud.aws.stack.auto=false
cloud.aws.region.auto=true
s3.bucket.name.photos.profiles:repo-user-bucket

eureka.client.service-url.defaultZone=http://192.168.99.100:8761/eureka/
eureka.client.initialInstanceInfoReplicationIntervalSeconds=5
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseExpirationDurationInSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=5

Environment
Java version: Java 8
SDK: ws-sdk-java/1.11.415 Linux/4.4.86-boot2docker

What could be the problem?
Thanks in advance!
